# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master

pool:
  vmImage: ubuntu-latest

variables:
  EC2_PUBLIC_IP: ''  # Populated dynamically
  SSH_USER: 'ec2-user'  # Default Amazon Linux user
  SSH_PRIVATE_KEY: $(mySShPrivateKey)  # Replace with actual variable name

steps:
  # Step 1: Install Terraform (Fully Qualified Name)
  - task: JasonBJohnson.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@2
    inputs:
     terraformVersion: 'latest'

  - script: |
      terraform init
      terraform validate
      terraform plan -out=tfplan
      terraform apply -auto-approve tfplan
    displayName: "Run Terraform Commands"

  # Step 6: Install SSH Key (Consider alternative to disabling StrictHostKeyChecking)
  - task: InstallSSHKey@0
    inputs:
      sshPublicKey: $(SSH_PRIVATE_KEY)

  # Step 7: SSH into EC2 and Clone GitHub Repositories
  - script: |
      ssh -i $(SSH_PRIVATE_KEY) $(SSH_USER)@$(EC2_PUBLIC_IP) << 'EOF'
      sudo yum update -y
      sudo yum install -y python3 git
      git clone https://github.com/your-user/your-dash-app-repo.git /home/ec2-user/dash_app
      git clone https://github.com/your-user/your-flask-api-repo.git /home/ec2-user/flask_api
      EOF
    displayName: "Clone Dash App and Flask API from GitHub"

  # Step 8: Install Dependencies and Run Applications
  - script: |
      ssh -i $(SSH_PRIVATE_KEY) $(SSH_USER)@$(EC2_PUBLIC_IP) << 'EOF'
      pip3 install -r /home/ec2-user/dash_app/requirements.txt
      pip3 install -r /home/ec2-user/flask_api/requirements.txt
      nohup python3 /home/ec2-user/dash_app/app.py > /home/ec2-user/dash_app.log 2>&1 &
      nohup python3 /home/ec2-user/flask_api/api.py > /home/ec2-user/flask_api.log 2>&1 &
      EOF
    displayName: "Install Dependencies and Start Applications"